name: Release

on:
  push:
    branches:
      - main
    # paths:
    #   - "Cargo.toml"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: rust
