name: Release

on:
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"

permissions:
  contents: write
  pull-requests: write

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: rust

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Release Crate
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cargo publish --token ${{ secrets.CARGO_PUBLISH_TOKEN }}
